# Kaigate 配置文件示例

# 服务配置
server:
  http_addr: "0.0.0.0:9001"     # HTTP服务监听地址
  ws_addr: "0.0.0.0:9002"        # WebSocket服务监听地址
  admin_addr: "0.0.0.0:9003"     # 管理接口监听地址
  debug: false                   # 是否启用调试模式
  conn_timeout: 30               # 连接超时时间(秒)
  rw_timeout: 60                 # 读写超时时间(秒)

# 日志配置
log:
  level: "debug"                  # 日志级别: debug, info, warn, error
  format: "text"                 # 日志格式: text, json
  file: "logs/kaigate.log"       # 日志文件路径
  stdout: true                   # 是否输出到标准输出

# WebSocket配置
websocket:
  heartbeat_interval: 30         # 心跳间隔(秒)
  max_connections: 1000          # 最大连接数

# 路由配置
router:
  enable_rate_limit: true        # 是否启用限流
  default_rate_limit: 100        # 默认限流值(每秒请求数)
  circuit_break: true            # 是否启用熔断
  circuit_break_threshold: 50    # 熔断阈值(错误率百分比)

# 代理路由配置 - 可配置多个代理路由，无需修改代码
proxy_routes:
  # 示例1: 将/deepsearch请求转发到localhost:8301
  - path: /send
    target_url: "http://localhost:8301"
    enable: true

  - path: /apple
    target_url: "http://localhost:8301"
    enable: true

  - path: /deepsearch
    target_url: "http://localhost:8301"
    enable: true
  
  # 示例2: 将/search请求转发到另一个服务
  - path: /search
    target_url: "http://localhost:8302"
    enable: true
  
  # 示例3: 一个禁用的代理路由
  - path: /api/external
    target_url: "http://api.example.com"
    enable: false